apiVersion: v1
kind: Secret
metadata:
  name: sqlserver-secret
  namespace: sargent-nexus
type: Opaque
stringData:
  sa-password: "<SA_PASSWORD>"
  connection-string: "Server=sargent-nexus-sqlserver;Database=SargentNexus;User Id=sa;Password=<SA_PASSWORD>;TrustServerCertificate=True"
