apiVersion: v1
kind: Service
metadata:
  name: sargent-nexus-client
  namespace: {{ .Values.namespace.name }}
spec:
  type: ClusterIP
  selector:
    app: sargent-nexus-client
  ports:
    - name: http
      port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
