apiVersion: v1
kind: ConfigMap
metadata:
  name: sargentnexus-runtime-config
data:
  EnvironmentName: dev
  PublicBaseUrl: https://sargentnexus-dev.example.com
  ApiPublicBaseUrl: https://sargentnexus-dev.example.com/api/v1
  AspNetCoreEnvironment: Development
  ApiLogLevelDefault: Debug
  ClientLogLevelDefault: Debug
  SqlServerStorageSize: 10Gi
  SqlServerStorageClassName: standard