apiVersion: v1
kind: ConfigMap
metadata:
  name: sargent-nexus-api-config
  namespace: {{ .Values.namespace.name }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.api.config.aspNetCoreEnvironment | quote }}
  ASPNETCORE_URLS: {{ .Values.api.config.aspNetCoreUrls | quote }}
  Swagger__Enabled: {{ .Values.api.config.swaggerEnabled | quote }}
